- name: load the index.html to webserver
  hosts: webservers
  become: true
  tasks:
    - name: copy the html to webserver
      copy: 
       src: /var/www/html/index.html
       dest: /var/www/html/index.html
      notify: restart_httpd   
  handlers:
    - name: restart_httpd
      service:
        name: httpd
        enabled: true
        state: started

        
