- name: Install firewall and enable
  hosts: webservers
  become: true
  tasks: 
    - name: install latest firewall
      yum:
        name: firewalld
        state: latest
    - name: enable firewalld
      service: 
        name: firewalld
        enabled : true
        state: started
  
