- name: play to install httpd
  hosts: webservers
  become: true
  tasks:
  - name: install latest httpd version
    yum: 
      name: httpd
      state: latest
  - name: web server is enabled
    service:
      name: httpd
      enabled: true
  - name: httpd is started
    service:
      name: httpd
      state: started
      enabled: true
